serverAddr = "123.60.8.109"   #服务器地址
serverPort = 7000   #服务器端口
auth.method = "token"   #服务端连接身份认证，默认token
auth.token = "951026"   #服务端token密码，密码不正确将无法连接服务器
transport.tls.enable = false   #是否和服务端之间启用TLS连接
transport.tls.disableCustomTLSFirstByte = false
#默认为true，当配置为true时，无法和vhostHTTPSPort端口复用
 
[[proxies]]
name = "ssh"   #隧道名称，可自定义，不能重复
type = "tcp"   #隧道类型，可用tcp, udp, http, https, tcpmux, stcp, sudp, xtcp
localIP = "127.0.0.1"   #本地IP地址，如果是本机就127.0.0.1
localPort = 22   #本地端口，本地服务端口，比如mc服务器端口25565
remotePort = 2200    #远程端口，连接隧道时用的端口
transport.useEncryption = true   #传输加密，加密算法采用 aes-128-cfb
transport.useCompression = true   #传输压缩，压缩算法采用 snappy

[[proxies]]
name = "remote"   #隧道名称，可自定义，不能重复
type = "tcp"   #隧道类型，可用tcp, udp, http, https, tcpmux, stcp, sudp, xtcp
localIP = "127.0.0.1"   #本地IP地址，如果是本机就127.0.0.1
localPort = 3389   #本地端口，本地服务端口，比如mc服务器端口25565
remotePort = 33890    #远程端口，连接隧道时用的端口
transport.useEncryption = true   #传输加密，加密算法采用 aes-128-cfb
transport.useCompression = true   #传输压缩，压缩算法采用 snappy


